# Generated by Django 5.2.11 on 2026-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_failedtask_csvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarreading',
            name='beat_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='solarreading',
            constraint=models.UniqueConstraint(fields=('plant', 'timestamp'), name='unique_plant_timestamp'),
        ),
    ]
