apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  AIRFLOW__WEBSERVER__SECRET_KEY: "your-static-secret-key-here"
  AIRFLOW__CORE__HOSTNAME_CALLABLE: socket:getfqdn
  AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
  DJANGO_BASE_URL: "http://172.20.0.2:8000"  # ← replace with your actual IP
  AIRFLOW_REPORTS_TOKEN: "dev-airflow-token"
  AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE: "false"
