apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: solar-monitor-airflow:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "solar_monitor.settings"